-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.0.240.2
-- Module  Version: 5.4
-- Sat Jan 14 01:13:14 2023

-- parameterized module component declaration
component rom_EBR_00
    port (Address: in  std_logic_vector(5 downto 0); 
        OutClock: in  std_logic; OutClockEn: in  std_logic; 
        Reset: in  std_logic; Q: out  std_logic_vector(31 downto 0));
end component;

-- parameterized module component instance
__ : rom_EBR_00
    port map (Address(5 downto 0)=>__, OutClock=>__, OutClockEn=>__, 
        Reset=>__, Q(31 downto 0)=>__);
